baseURL = "https://mau-me.github.io/maume_page/"
title = "Maume"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
author = "Mauricio Menezes"
description = "Mauricio Menezes's personal website"
keywords = "blog,developer,personal"
info = ["Backend Developer"]
avatarURL = "images/profile.gif"
dateFormat = "January 2, 2006"
since = 2013
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to use Pirsch(https://pirsch.io) for analytics, add this section
# [params.pirsch]
# code = "ABCDE"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/mau-me/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 2
url = "https://github.com/mau-me/"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-solid fa-at"
weight = 3
url = "mailto:mauriciosm95@gmail.com"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 4
url = "https://twitter.com/olaf_mau"

[[params.social]]
name = "Instagram"
icon = "fa fa-2x fa-instagram"
weight = 5
url = "https://www.instagram.com/olaf_mau/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 6
url = "https://medium.com/@mauriciosm95"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

[[languages.en.menu.main]]
name = "Resume"
weight = 4
url = "https://github.com/mau-me/_curriculo/raw/main/cv.pdf"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[languages.pt-br]
languageName = ":brazil:"
title = ""

[languages.pt-br.params]
author = "Mauricio Menezes"
info = "Desenvolvedor Backend"
description = "Site pessoal de Mauricio Menezes"
keywords = "blog,desenvolvedor,pessoal"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

# [[languages.pt-br.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.pt-br.menu.main]]
# name = "Projetos"
# weight = 3
# url = "projects/"

[[languages.pt-br.menu.main]]
name = "Currículo"
weight = 4
url = "https://github.com/mau-me/_curriculo/raw/main/cv.pdf"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 5
url = "contact/"
